// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN5PE5AoxstVSW39l9hPsoFV1JCgA3KCI',
    appId: '1:632311980662:web:07ace801f2f74259c2f557',
    messagingSenderId: '632311980662',
    projectId: 'one-hp-54e38',
    authDomain: 'one-hp-54e38.firebaseapp.com',
    storageBucket: 'one-hp-54e38.appspot.com',
    measurementId: 'G-W9Y72EKHRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpEx7NPtp_JwzLtWVqMA4JIIQ7hMeFF4E',
    appId: '1:632311980662:android:44996d52eac7916dc2f557',
    messagingSenderId: '632311980662',
    projectId: 'one-hp-54e38',
    storageBucket: 'one-hp-54e38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFx_ZMQSFQgQSxDPqHWDoHwx2-gabjRdw',
    appId: '1:632311980662:ios:18f1f04933957de0c2f557',
    messagingSenderId: '632311980662',
    projectId: 'one-hp-54e38',
    storageBucket: 'one-hp-54e38.appspot.com',
    iosClientId: '632311980662-ttm0efvs4v1c4mrpticnq0js8ptk8r16.apps.googleusercontent.com',
    iosBundleId: 'com.eymericsertgoz.onehp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFx_ZMQSFQgQSxDPqHWDoHwx2-gabjRdw',
    appId: '1:632311980662:ios:0227148c79a897c5c2f557',
    messagingSenderId: '632311980662',
    projectId: 'one-hp-54e38',
    storageBucket: 'one-hp-54e38.appspot.com',
    iosClientId: '632311980662-qkhbbca4gbq5ujfgeuq6ojtlp7iu9cpg.apps.googleusercontent.com',
    iosBundleId: 'com.example.oneHp.RunnerTests',
  );
}
